// <auto-generated />
using M8Assignment.Admin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M8Assignment.Migrations
{
    [DbContext(typeof(AirportContext))]
    [Migration("20220306223625_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("M6Assignment.Models.Airport", b =>
                {
                    b.Property<int>("AirportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirportID");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            AirportID = 1,
                            Code = "GSP",
                            Name = "Greenville-Spartanburg-Anderson"
                        },
                        new
                        {
                            AirportID = 2,
                            Code = "GMU",
                            Name = "Greenville Downtown Airport"
                        },
                        new
                        {
                            AirportID = 3,
                            Code = "GYH",
                            Name = "Donaldson Field Airport"
                        },
                        new
                        {
                            AirportID = 4,
                            Code = "SPA",
                            Name = "Spartanburg Downtown Airport"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
